package com.blogspot.jpdevelopment.batch;

import javax.xml.namespace.*;
import javax.xml.ws.*;
import java.net.*;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2016-12-25T20:13:40.553+01:00
 * Generated source version: 3.1.0
 * 
 */
@WebServiceClient(name = "BatchJobServiceService", 
                  wsdlLocation = "http://localhost:9000/services/toplife/ws/batch/BatchJobServicePort?wsdl",
                  targetNamespace = "http://batch.ws.toplife.schantz.com/") 
public class BatchJobServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://batch.ws.toplife.schantz.com/", "BatchJobServiceService");
    public final static QName BatchJobServicePort = new QName("http://batch.ws.toplife.schantz.com/", "BatchJobServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9000/services/toplife/ws/batch/BatchJobServicePort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BatchJobServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:9000/services/toplife/ws/batch/BatchJobServicePort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BatchJobServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BatchJobServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BatchJobServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public BatchJobServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BatchJobServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BatchJobServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns BatchJobService
     */
    @WebEndpoint(name = "BatchJobServicePort")
    public BatchJobService getBatchJobServicePort() {
        return super.getPort(BatchJobServicePort, BatchJobService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BatchJobService
     */
    @WebEndpoint(name = "BatchJobServicePort")
    public BatchJobService getBatchJobServicePort(WebServiceFeature... features) {
        return super.getPort(BatchJobServicePort, BatchJobService.class, features);
    }

}
