package com.blogspot.jpdevelopment.batch;

import javax.jws.*;
import javax.xml.ws.*;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2016-12-25T20:13:40.521+01:00
 * Generated source version: 3.1.0
 * 
 */
@WebService(targetNamespace = "http://batch.ws.toplife.schantz.com/", name = "BatchJobService")
public interface BatchJobService {

    @WebMethod
    @RequestWrapper(localName = "getBatchJobStatus", targetNamespace = "http://batch.ws.toplife.schantz.com/", className = "com.schantz.toplife.ws.batch.GetBatchJobStatus")
    @ResponseWrapper(localName = "getBatchJobStatusResponse", targetNamespace = "http://batch.ws.toplife.schantz.com/", className = "com.schantz.toplife.ws.batch.GetBatchJobStatusResponse")
    @WebResult(name = "return", targetNamespace = "")
    public BatchJobStatusResult getBatchJobStatus(
		    @WebParam(name = "userId", targetNamespace = "")
				    String userId,
		    @WebParam(name = "activityRequestUid", targetNamespace = "")
				    String activityRequestUid
    );

    @WebMethod
    @RequestWrapper(localName = "stopBatchJob", targetNamespace = "http://batch.ws.toplife.schantz.com/", className = "com.schantz.toplife.ws.batch.StopBatchJob")
    @ResponseWrapper(localName = "stopBatchJobResponse", targetNamespace = "http://batch.ws.toplife.schantz.com/", className = "com.schantz.toplife.ws.batch.StopBatchJobResponse")
    public void stopBatchJob(
		    @WebParam(name = "userId", targetNamespace = "")
				    String userId,
		    @WebParam(name = "activityRequestUid", targetNamespace = "")
				    String activityRequestUid
    );

    @WebMethod
    @RequestWrapper(localName = "startBatchJob", targetNamespace = "http://batch.ws.toplife.schantz.com/", className = "com.schantz.toplife.ws.batch.StartBatchJob")
    @ResponseWrapper(localName = "startBatchJobResponse", targetNamespace = "http://batch.ws.toplife.schantz.com/", className = "com.schantz.toplife.ws.batch.StartBatchJobResponse")
    @WebResult(name = "return", targetNamespace = "")
    public BatchJobStartResult startBatchJob(
		    @WebParam(name = "userId", targetNamespace = "")
				    String userId,
		    @WebParam(name = "scheduleId", targetNamespace = "")
				    String scheduleId
    );
}
